apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-java-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: my-java-app
      sourceRef:
        kind: HelmRepository
        name: my-java-app
        namespace: default
      interval: 10m
  values:
    imagePullSecrets:
      - name: ghcr-auth
    image:
      repository: ghcr.io/bazoocaze/my-java-app
      tag: 1.0.19 # {"$imagepolicy": "default:my-java-app:tag"}
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hosts:
        - host: localhost
          paths:
            - path: /my-java-app(/|$)(.*)
              pathType: ImplementationSpecific
