apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.helmRelease.interval }}
  chart:
    spec:
      chart: {{ .Values.appName }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.appName }}
        namespace: {{ .Values.namespace }}
      interval: {{ .Values.helmRelease.chartInterval }}
  values:
    imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
    image:
      repository: {{ .Values.image.repository }}
      tag: {{ .Values.image.tag }} # {"$imagepolicy": "{{ .Values.namespace }}:{{ .Values.appName }}:tag"}
    ingress:
      enabled: {{ .Values.ingress.enabled }}
      className: "{{ .Values.ingress.className }}"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
      hosts:
        - host: {{ .Values.ingress.host }}
          paths:
            - path: {{ .Values.ingress.path }}
              pathType: {{ .Values.ingress.pathType }}