apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  image: {{ .Values.image.repository }}
  interval: {{ .Values.imageRepository.interval }}
  secretRef:
    name: {{ .Values.ociRepository.secretRef }}