apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  imageRepositoryRef:
    name: {{ .Values.appName }}
  policy:
    semver:
      range: {{ .Values.imagePolicy.semver | quote }}