apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: my-java-app2
  namespace: default
spec:
  imageRepositoryRef:
    name: my-java-app2
  policy:
    semver:
      range: "~1.0.0"